name: auto merge
on:
  pull_request_review_comment:
    types: [created]

jobs:
  merge:
    name: auto-merge dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]' && github.event.pull_request_review_comment.body == 'AUTO APPROVED'
    steps:
      - name: merge
        uses: actions/github-script@0.2.0
        with:
          script: |
            var interval = setInterval(github.checks.getSuite({
               owner: context.payload.repository.owner.login,
               repo: context.payload.repository.name,
               check_suite_id: context.payload.check_suite.number
             }).then(response => {
                 if (response.data.conclusion === 'success') {
                     github.pullRequests.merge({
                         owner: context.payload.repository.owner.login,
                         repo: context.payload.repository.name,
                         pull_number: context.payload.pull_request.number
                     }).then(() => {
                         clearInterval(interval)
                     })
                 }
             }), 1000);
          github-token: "${{ secrets.GITHUB_TOKEN }}"
